DROP TABLE IF EXISTS contacts;

CREATE TABLE contacts(
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(20) NOT NULL,
    lastname VARCHAR(20) NOT NULL,
    image VARCHAR(20) NOT NULL,
    email VARCHAR(20) NOT NULL,
    phone INT NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updateData TIMESTAMP NOT NULL DEFAULT NOW()
);
